vita-import-parse.c, vita-import.h
Jansson fails to parse if given extremely large strings of json data, to make it parse, just pass the FILE pointer to Jansson so it can stream things in on its own.
=> Parsing fails with extremely large databases

cmake/Modules/Findlibzip.cmake, src/CMakeLists.txt
libzip keeps its configuration header in "lib/libzip/include", this is picked up fine by cmake, but our cmake script neglects adding it to the include dirs.
ZIP_STATIC must be defined for windows builds when using a static version of libzip.
=> Improved CMake scripts for libzip

src/CMakeLists.txt
By default libyaml will try to use dll import which causes undefined symbols when linking. ```YAML_DECLARE_STATIC``` when defined will prevent dll linkage attempts.
=> add YAML_DECLARE_STATIC define when doing a windows build

src/vita-elf.c
This fixes a bug that causes moduleinfo to be at a mis-aligned address when the last element in the main segment is of unaligned size.
=> force segment size to be 0x10 aligned.

src/vita-elf-create.c
vita-elf-create modifies the segment sizes `memsz` causing a segfault because the value is expected to remain the same between `mmap()` and `munmap()`. The patch saves the segment sizes, then restores them before freeing these segments.
=> fix segfault in vita-elf-create caused by mmap/munmap segment size mismatch

src/sce-elf.c, src/vita-elf-create.c, src/vita-elf.c, src/vita-elf.h, src/vita-libs-gen.c
Modified #69 to use a realloc and memset instead of a second malloc and a memcpy. This is the advice of the code review.
=> Remove db.json requirement on vita-elf-create

src/vita-export-parse.c
We need to return 0 for success.
It causes troubles at parsing the yaml, and we do not return 0, it could be any number/its undefined. Normally the compiler should warn you about that, but I guess the warning level wasnt high enough.
With this fix I'am now able to build https://github.com/yifanlu/taiHEN under cygwin
=> Missing needed returns

src/sce-elf.c
Fixes #72 
We're changing section names from `.vitalink.fstubs.SceWhatever` to `.text.fstubs.SceWhatever`. Since new name is always shorter than the old one, it was assumed a buffer overrun is not possible. However, it still can happen with malformed names, e.g. trying to change `.vitalink.fstubs` => `.text.fstubs.fstubs`. Before we would segfault, with this patch it will truncate the name to fit, since it's the best thing we can do against malformed section names (the resulting elf should work anyway).
=> Fix segfault when rewriting section names in sce_elf_rewrite_stubs

src/vita-elf.c
=> vita-elf: Fix build when MAP_NORESERVE is not available

cmake_toolchain/vita.toolchain.cmake
On newer cmake (as seen on 3.10.1), this results in it not finding `make`,
resulting in build errors on every homebrew.
=> vita.toolchain.cmake: Remove CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY

src/vita-import-parse.c, src/vita-import.c, src/vita-import.h, src/vita-libs-gen.c
if filled `firmware` in the root and this value isn't `3.60`,
will attach postfix before `_stub.a`
eg;
pass to
```
firmware: 3.67
```
all generated libs will end with `_367_stub.a` like `libSceCpuForKernel_367_stub.a`
Related vitasdk/vita-headers#300
=> vita-libs-gen: Use firmware field

cmake_toolchain/vita.cmake
`add_custom_target` isn't suited for running command that output stuff.
The [documentation](https://cmake.org/cmake/help/latest/command/add_custom_target.html) states that
> The target has no output file and is always considered out of date even if the commands try to create a file with the name of the target.
So I kept the target only to force the vpk and eboot to be built by default, but it does not rebuild it if it is not necessary.
=> vita.cmake: avoid rebuilding unnecessarily vpk and eboot

src/yamltree.c
Hi all,
There are memory leak issues found by Qihoo360 CodeSafe Team.
Details as bellow:
in function 'process_sequence()' and 'process_mapping()', when they try to return NULL, the memory allocated is not freed.
Free the memory to repair memory leak.
Cheers
Qihoo360 CodeSafe Team
=> Memory Leak Repair

cmake_toolchain/vita.toolchain.cmake
This matches the behaviour of the Android toolchain cmake file [1] and it allows providing self-compiled libraries (not part of vitasdk/vdpm) as argued in this git issue [2].
[1] https://android.googlesource.com/platform/ndk/+/master/build/cmake/android.toolchain.cmake#281
[2] https://github.com/android-ndk/ndk/issues/517
=> Allow overwriting of CMAKE_FIND_ROOT_PATH_MODE_LIBRARY & INCLUDE

cmake_toolchain/vita.cmake
this patch would recover the broken name since #120
this patch will print the warning about `circular dependency dropped`
but would work properly.
actually, we should give the right name to target (#129 still has wrong name)
follow the 2011 cmake newgroup thread & cmake issue
- https://cmake.org/pipermail/cmake/2011-March/043375.html
- https://gitlab.kitware.com/cmake/cmake/issues/18627
=> vita.cmake: Give the same name as custom_command

src/sce-elf.h
it occurs a compile-linking error with gcc 10.1
=> Fix multiple definition of `sce_elf_stub_func'

CMakeLists.txt, build.sh, cmake/Modules/Findlibelf.cmake, cmake/Modules/Findlibyaml.cmake, cmake/Modules/Findlibzip.cmake, cmake/Modules/Findzlib.cmake
the problem is modern *nix system uses GNU elfutils instead legacy libelf.
these two library lost backward compatibilty (they uses different enum value),
and out buildscripts & vita-toolchian only has compatibility with legacy version.
if system environment was mismatched, it occurs assertion errors (with local buildscripts result)
```
vita-elf-create: dest = elf_begin(fileno(*file), ELF_C_WRITE, NULL) failed: Request error: invalid ELF_C_* argument
vita-elf-create: Assertion failed: (dest = elf_utils_copy_to_file(args.output, ve->elf, &outfile))
```
or segfault (with manual built version `vita-make-fself`)
this patch will find library properly using hacky environ overwritten in the cmake scripts
=> Update build.sh script and cmake chain for fixing libelf conflict

src/sce-elf-defs.h, src/sce-elf.c, src/vita-elf-create.c, src/vita-elf-export.c, src/vita-elf.c, src/vita-elf.h, src/vita-export-parse.c, src/vita-export.h, src/vita-import-parse.c, src/vita-import.c, src/vita-import.h, src/vita-libs-gen.c, src/vita-make-fself.c
=> Swapped usage of library and module terminology.

src/sce-elf.c
Error from commit 64dc1cc causing every imported function to have a separate sce_module_imports struct.
Thanks to @Princess-of-Sleeping for noticing the issue, and @frangarcj for identifying the cause.
=> Fix error in import parsing.

.gitignore, src/sce-elf-defs.h, src/sce-elf.c, src/sce-elf.h, src/vita-elf-create.c
Moved SceProcessParam fields to a separate struct. Added SceLibcParam struct.
Added support for user definition of process param and libc param fields.
Switched to individual user definition of SceLibcParam fields, rather than user definition of the entire struct.
Added module_sdk_version export, variable exists in the sce_module_info struct.
Libc heap allocation function names were found here:
https://github.com/Olde-Skuul/burgerlib/blob/master/source/vita/brvitamemory.h
=> Better SceLibcParam support and add support for user defined process params.

pkgconfig/arm-vita-eabi-pkg-config
That should fix https://github.com/vitasdk/vdpm/issues/69
Although, having proper prefix would still be nice.
=> Allow pkg-config to auto-detect and override prefix

cmake_toolchain/vita.toolchain.cmake
Make CMake use VitaSDK's pkg-config wrapper instead of the system one
=> vita.toolchain.cmake: Set pkg-config path

cmake_toolchain/vita.toolchain.cmake
Hi, I'm running the latest cmake:
```sh
$ cmake --version
cmake version 3.20.1
```
And I keep getting this annoying warning:
```
cmake ../.. 
CMake Deprecation Warning at /usr/local/vitasdk/share/vita.toolchain.cmake:33 (cmake_minimum_required):
Compatibility with CMake < 2.8.12 will be removed from a future version of
CMake.
Update the VERSION argument <min> value or use a ...<max> suffix to tell
CMake that the project does not need compatibility with older versions.
Call Stack (most recent call first):
Debug/vita/CMakeFiles/3.20.1/CMakeSystem.cmake:6 (include)
CMakeLists.txt:30 (project)
```
Wondering if we could do a bump?
=> chore: bump minimum cmake

cmake_toolchain/vita.cmake
This fixes a failure when NAME contains special characters, such as parenthesis.
=> vita.cmake: Pass VERBATIM option to add_custom_command when generating SFO

cmake_toolchain/vita.cmake
Although, cmake docs doesn't state anything relevant (except that you can use expressions in 3.20), using BYPRODUCTS on cmake < 3.20 seems to randomly break builds.
Because 3.20 is fairly "fresh" (even ubuntu 20 still has 3.16), i've added version check to skip using BYPRODUCTS on cmake < 3.20
=> Do not use BYPRODUCTS on cmake < 3.20

src/sce-elf.c, src/vita-export-parse.c
Deprecates the use of 'modules' in the export configuration.
=> Adjust the module/library terminology

src/CMakeLists.txt, src/sha256.h, src/yamltree.c
1) Fix asprintf definition in yaml
2) Make sha256 funcs public. Fixes mingw build.
=> Fix mingw build

src/sce-elf-defs.h, src/sce-elf.c, src/vita-elf-create.c, src/vita-elf.c, src/vita-elf.h
Since current vita-toolchian always exports module_sdk_version and its value is fixed at 0x3570011, running programs on older firmware versions is a very cumbersome procedure using some external tools. and had to change the module_sdk_version.
However this PR make module_sdk_version as a module export from a global variable in the user controllable project source code.
toolchain until now -> module_sdk_version is 0x3570011 always because toolchain fixed it
```
const SceUInt32 module_sdk_version = 0x3600011;
int module_start(){
... code
}
```
This PR -> module_sdk_version is 0x3600011 from source code
```
const SceUInt32 module_sdk_version = 0x3600011;
int module_start(){
... code
}
```
However, this PR changes not only module_sdk_version, but also fw_version in process_param/libc_param …
=> Implement module_sdk_version dependent on user global variable

src/vita-mksfoex.c
I found this bug while I was reading over this file. The code is pretty old and kinda janky. This fixes vita-mksfoex on big endian, if anyone ever attempts to use that.
=> vita-mksfoex: Fix 32-bit write to 8-bit field

.github/workflows/compilation.yml
https://github.com/vitasdk/vita-toolchain/actions/runs/3851676888
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/upload-artifact@v2
> The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
=> Fix GitHub Actions warnings

pkgconfig/arm-vita-eabi-pkg-config
There probably isn't an issue with this right now, but it's nice to have the ability to just use VITASDK in pc files and have it work in all cases.
=> Make sure using VITASDK variable in pc files always works

src/CMakeLists.txt
I've found strict aliasing violations regularly occuring in the code. Example:
https://github.com/vitasdk/vita-toolchain/blob/bbb2c95d41cd4037df86529217387979745426b6/src/vita-libs-gen-2.cpp#L545-L546
=> Add -fno-strict-aliasing flag

src/vita-elf-create/sce-elf.c, src/vita-elf-create/sce-elf.h, src/vita-elf-create/vita-elf-create.c, src/vita-elf-create/vita-elf.c, src/vita-elf-create/vita-elf.h, src/vita-export-parse.c, src/vita-export.h
- The image module (.elf) no longer requires rel info completely.
- Automatically generate process_param according to process_image/image module.
- module_info alignment to 4-bytes. (So should not be encount to `vita-elf-create: elf_update(dest, ELF_C_WRITE) >= 0 failed: Layout error: overlapping sections`)
- Some tweak.
=> Make a select the appropriate scenario for velf

README.md, src/vita-elf-create/elf-create-argp.c, src/vita-elf-create/vita-elf-create.c
=> Added stub privilege checker part 3

src/vita-elf-create/vita-elf-create.c
The stub privilege check was tested on rebuilt SCE stubs without "packages" repo stubs.
=> Disable stub privilege check

cmake_toolchain/vita.toolchain.cmake
`PKG_CONFIG_EXECUTABLE` needs to be cached, such that the [`find_program`](https://github.com/Kitware/CMake/blob/bc82d62b1bb484aabb1fdbb563c44f6e7cffb55f/Modules/FindPkgConfig.cmake#L62-L66) in [`FindPkgConfig`](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html) will use the custom one.
Without this change, [SDL](https://github.com/libsdl-org/SDL/pull/8366) cannot use [`pkg_check_modules`](https://cmake.org/cmake/help/latest/module/FindPkgConfig.html#command:pkg_check_modules) to find the dependencies of the static ffmpeg libraries.
=> vita.toolchain.cmake: cache pkg-config path

.github/workflows/compilation.yml, CMakeLists.txt, cmake_toolchain/vita.cmake, src/vita-libs-gen-2/vita-libs-gen-2.cpp, src/vita-libs-gen/vita-libs-gen.c
=> Fix deprecation warnings

src/vita-elf-create/elf-create-argp.c, src/vita-elf-create/sce-elf.c
Fixes lack of a default module_start export for process image modules using an export config
Undoes commit e0138e4
=> Fix lack of default start export
