vitasdk/vita-toolchain

- src/CMakeLists.txt
- src/vita-elf-create.c
> Add support for default JSON files.

- src/elf-utils.c
- src/sce-elf-defs.h
- src/sce-elf.c
- src/sce-elf.h
1. Some relocation issues
2. Large .bss size (fixes #6)
> Fixed various bugs in vita-create-elf

- src/elf-utils.c
- src/vita-elf.c
Should fix problems with EXIDX segments causing ELF to not load.
> Only copy PT_LOAD segments to SCE ELF output.

- src/elf-utils.c
- src/elf-utils.h
- src/sce-elf-defs.h
- src/sce-elf.c
- src/sce-elf.h
- src/vita-elf-create.c
- src/vita-elf.c
- src/vita-elf.h
- src/vita-import-parse.c
- src/vita-import.c
- src/vita-make-fself.c
Reverts vitasdk/vita-toolchain#4
> Revert "Fix bugs"

- src/CMakeLists.txt
- src/vita-make-fself.c
> Added fself compression support

- src/sce-elf.c
- src/vita-elf.c
- src/vita-import.h
- src/vita-libs-gen.c
vita-libs-gen now generates cmake rather than makefile.
weak stubs are created for only user space libraries.
> add support for prx weak imports.

- .travis.yml
- build.sh
> Add travis support

- build.sh
> Improve build.sh

- build.sh
- src/CMakeLists.txt
- src/build/vita-toolchain-public.h
- src/vita-elf-export.c
- src/vita-export.h
- src/vita-import.h
- src/vita-toolchain-public.h
- src/yamltree.h
- src/yamltreeutil.h
I open A new pull request with the same change with #99 because the build failure happend after merging it is apparently not caused by the change.
See #105 for the details of the issue.
> Move some components in their own libraries (#99)

- cmake_toolchain/vita.cmake
> vita.cmake: rebuild vpk when resources are changed

- src/vita-pack-vpk.c
This add Folder packing in vita-pack-vpk
> Add Folder packing in vita-pack-vpk

- src/vita-libs-gen.c
1. added install to cmake generator
2. fixed makefile generator for non-360 libraries (this makes makefile working for db_367.yml in vitasdk/vita-headers#300)
3. made makefile not generating empty stubs (the same behavior as cmake)
> vita-libs-gen fixes

- cmake_toolchain/vita.cmake
See issue https://github.com/vitasdk/vita-toolchain/issues/132
> Fix CMake dependencies and avoid target/command name collisions

- cmake_toolchain/vita.cmake
> Fix circular dependencies between target and command

- src/vita-export-parse.c
for To replace a module in the system and To make up for some export deficiencies.
> Added patch so that can assign any NID to function

- src/sce-elf.c
Will allow use of SceLibc heap. sceLibcParam struct must be defined by user in code.
Credit to @frangarcj for designing the implementation.
> Add SceLibcParam support.

- src/vita-elf.c
This PR crash patch: https://github.com/vitasdk/buildscripts/pull/78
> Add out of range ref patch

- cmake_toolchain/vita.cmake
- src/vita-make-fself.c
Add flag for vita-make-fself and cmake to disable ASLR.
> Allow disabling ASLR.

- cmake_toolchain/vita.cmake
- cmake_toolchain/vita.toolchain.cmake
This allows to properly clean up self/velf/vpk on `make clean`
> Bump minimal cmake version and use BYPRODUCTS

- src/vita-export-parse.c
I added the ability to freely assign NIDs to functions and variables in #153 and #158, but at that time I used a global counter to prevent NID conflicts, which was a big problem.
The format is probably fine. (`%s_%08X`)
The problem is that it interferes with other libraries and produces a NID that ignores the version.
Suppose you have the following sample.
```
SampleModule:
attributes: 0
version:
major: 1
minor: 1
main:
start: module_start
modules:
TestLibForDriver:
version: 1
syscall: false
functions:
- test_func
- test_func_new_add
- test_func_base
TestLibForKernel:
syscall: false
functions:
- test_func2: 0xFAFAFAFA
- test_func3
```
If you add a new `test_func_new_add`, all the NIDs of the entries below it will be changed, and compatibility will be significantly lost.
Therefore, we …
> Fix the NID generation algorithm

- src/vita-elf-export.c
> Fix fd leak

- src/sce-elf.c
- src/sce-elf.h
- src/vita-elf-create.c
- src/vita-elf.c
- src/vita-elf.h
- src/vita-libs-gen.c
Hasn't been tested significantly, but importing one variable from SceLibc and another from SceLibJson does seem to work fine
> Add support for variable imports

- src/self.h
- src/vita-make-fself.c
Instead of PR #204.
The difference from PR #204 is that the developer doesn't need to specify any flags, every self that is output has an elfdigest.
> Add support elf digest

- src/sce-elf-defs.h
- src/sce-elf.c
- src/sce-elf.h
- src/vita-elf-create.c
This change has been tested, but it's enough to break some things.
Therefore, it should be reviewed with great care.
> Added support to old format process_param

- src/fs_list.c
- src/fs_list.h
https://github.com/vitasdk/vita-toolchain/pull/232
> Update fs_list.* license

- src/CMakeLists.txt
- src/fs_list.c
fixed fs_list non unix build with help from @isage (https://github.com/vitasdk/vita-toolchain/pull/234#issuecomment-1593573616)
> Fixed fs_list non unix build
